# Generated by Django 4.0.4 on 2022-07-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_customer_customermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectedfreelancer',
            old_name='account_linked',
            new_name='enabled',
        ),
    ]
