# Generated by Django 4.0.4 on 2022-07-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transactionmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='payment_method_types',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
