# Generated by Django 4.0.4 on 2022-07-17 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_transactionmodel_payment_method_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='payment_method_types',
        ),
        migrations.CreateModel(
            name='DepositModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=100)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payments.transactionmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
