# Generated by Django 4.0.4 on 2022-07-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_depositmodel_for_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositmodel',
            name='status',
            field=models.CharField(choices=[('Released', 'Released'), ('On Hold', 'On Hold'), ('Refunded', 'Refunded')], default='On Hold', max_length=100),
        ),
    ]
