# Generated by Django 4.0.4 on 2022-07-17 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0014_alter_depositmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='transaction_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
