# Generated by Django 4.0.4 on 2022-07-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_transactionmodel_transaction_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='transactionmodel',
            options={'ordering': ['-id']},
        ),
    ]
