# Generated by Django 4.0.4 on 2022-08-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_feemodel_taxmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='type',
            new_name='types',
        ),
    ]
