# Generated by Django 4.0.4 on 2022-05-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_proposal_delete_proposol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('ON', 'Ongoing'), ('COM', 'Completed'), ('CAN', 'Cancelled')], default='PEN', max_length=250),
        ),
    ]
