# Generated by Django 4.0.4 on 2022-05-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_user_project_hired_project_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price_status',
            field=models.CharField(choices=[('FIXED', 'FIXED'), ('NEGOTIATE', 'Can Negotiate')], default='NEGOTIATE', max_length=250),
        ),
    ]
