# Generated by Django 4.0.4 on 2022-05-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_price_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
