# Generated by Django 4.0.4 on 2022-05-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_options_project_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
