# Generated by Django 4.0.4 on 2022-05-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_expires_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='posted_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
