# Generated by Django 4.0.4 on 2022-05-19 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_project_end_date_project_experience_needed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='interviewing',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HiredModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hired_date', models.DateField(auto_now_add=True)),
                ('got_hired', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='got_hired', to=settings.AUTH_USER_MODEL)),
                ('hired_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hired', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_hires', to='projects.project')),
            ],
        ),
    ]
