# Generated by Django 4.0.4 on 2022-05-20 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_alter_project_interviewing_hiredmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='can_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='hired',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hired_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
