# Generated by Django 4.0.4 on 2022-05-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_can_apply_alter_project_hired'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='desired_skills',
            field=models.ManyToManyField(blank=True, to='projects.desiredexpertise'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_period',
            field=models.CharField(blank=True, choices=[('IS', 'Immediate Start'), ('OGD', 'On Given Date')], max_length=250),
        ),
    ]
