# Generated by Django 4.0.4 on 2022-06-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_reviews_options_alter_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_period',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('Active', 'Active'), ('ON', 'Ongoing'), ('COM', 'Completed'), ('CAN', 'Cancelled')], default='PEN', max_length=250),
        ),
    ]
