# Generated by Django 4.0.4 on 2022-06-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemodel',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
