# Generated by Django 4.0.4 on 2022-07-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_end_time_project_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payment_added',
            field=models.BooleanField(default=False),
        ),
    ]
