# Generated by Django 4.0.4 on 2022-07-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_payment_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='payment_added',
        ),
        migrations.AddField(
            model_name='project',
            name='employer_payment_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Refunded', 'Refunded')], max_length=20, null=True),
        ),
    ]
