# Generated by Django 4.0.4 on 2022-07-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_remove_project_payment_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employer_payment_status',
            field=models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Refunded', 'Refunded')], max_length=20, null=True),
        ),
    ]
