# Generated by Django 4.0.4 on 2022-07-29 15:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_project_employer_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
