# Generated by Django 4.0.4 on 2022-08-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_project_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
