# Generated by Django 4.0.4 on 2022-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_reviews_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
