# Generated by Django 4.0.4 on 2022-08-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_projectcategory_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
