# Generated by Django 4.0.4 on 2022-09-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='icon',
        ),
        migrations.AddField(
            model_name='membership',
            name='plans',
            field=models.ManyToManyField(to='membership.plan'),
        ),
    ]
