# Generated by Django 4.0.4 on 2022-09-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_remove_plan_icon_membership_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
