# Generated by Django 4.0.4 on 2022-09-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_plan_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
