# Generated by Django 4.0.4 on 2022-05-13 11:19

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='siteoption')),
                ('contact_email', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('Live', 'Live'), ('Down', 'Down'), ('Maintainance', 'Maintainance')], default='Live', max_length=20)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='siteoption')),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
