# Generated by Django 4.0.4 on 2022-06-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_alter_sitesetting_address_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, default='favicon.png', null=True, upload_to='siteoption'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_image',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to='siteoption'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(blank=True, default='batuwa', max_length=100, null=True),
        ),
    ]
