# Generated by Django 4.0.4 on 2022-07-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0004_staticpages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticPages',
        ),
    ]
