# Generated by Django 4.0.4 on 2022-08-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0005_delete_staticpages'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.CharField(choices=[('Live', 'Live'), ('Down', 'Down'), ('Maintainance', 'Maintainance')], default='Live', max_length=20)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
