# Generated by Django 4.0.4 on 2022-09-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0008_socialsetting_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='siteoption'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='siteoption'),
        ),
    ]
