# Generated by Django 4.0.4 on 2022-09-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0010_othersetting_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othersetting',
            name='media',
            field=models.CharField(blank=True, choices=[('Google_Analytics', 'Google_Analytics'), ('Google_Adsense', 'Google_Adsense'), ('Facebook_Messenger', 'Facebook_Messenger'), ('Facebook_Pixel', 'Facebook_Pixel'), ('Google_Recaptcha', 'Google_Recaptcha'), ('Cookies_Agreement', 'Cookies_Agreement')], max_length=20, null=True),
        ),
    ]
