# Generated by Django 4.0.4 on 2022-10-11 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('sitesettings', '0011_alter_othersetting_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('socialapp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialaccount.socialapp')),
                ('title', models.CharField(max_length=255)),
            ],
            bases=('socialaccount.socialapp',),
        ),
    ]
