# Generated by Django 4.0.4 on 2022-10-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('sitesettings', '0013_socialapplication_delete_custommodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialApplication',
            new_name='ExtendedSocialSetting',
        ),
        migrations.DeleteModel(
            name='SocialSetting',
        ),
    ]
