# Generated by Django 4.0.4 on 2022-09-23 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.review'),
        ),
    ]
