# Generated by Django 4.0.4 on 2022-09-25 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_subscriber_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='token',
            field=models.UUIDField(default=uuid.UUID('0b73b8a7-40c5-48bb-8c53-e6a4b555de74'), editable=False),
        ),
    ]
