# Generated by Django 4.0.4 on 2022-09-26 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_subscriber_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='token',
            field=models.UUIDField(default=uuid.UUID('eeeb15ca-53e2-4194-8a6d-fc60260d7919'), editable=False),
        ),
    ]
