# Generated by Django 4.0.4 on 2022-09-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_subscriber_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
