# Generated by Django 4.0.4 on 2022-05-13 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_reviews'),
        ('user', '0003_rename_bio_user_overview_user_address_user_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarked_people',
            field=models.ManyToManyField(related_name='bookmarked_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='bookmarked_projects',
            field=models.ManyToManyField(related_name='bookmared_projects', to='projects.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
