# Generated by Django 4.0.4 on 2022-05-13 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_bookmarked_people_user_bookmarked_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmarked_people',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
