# Generated by Django 4.0.4 on 2022-05-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='role',
        ),
    ]
