# Generated by Django 4.0.4 on 2022-05-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hourly_rate',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='overview',
            field=models.TextField(blank=True, default='Thinking of awesome bio'),
        ),
    ]
