# Generated by Django 4.0.4 on 2022-06-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employer', 'Employer'), ('Freelancer', 'Freelancer')], max_length=200),
        ),
    ]
