# Generated by Django 4.0.4 on 2022-06-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
