# Generated by Django 4.0.4 on 2022-06-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_activitylog_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-id']},
        ),
    ]
