# Generated by Django 4.0.4 on 2022-06-15 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_activitylog_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='behance',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='dribble',
        ),
        migrations.CreateModel(
            name='IdentityForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=150)),
                ('identiy_num', models.DateField(verbose_name='CNIC / Passport / NIN / SSN')),
                ('document', models.FileField(upload_to='identity_files')),
                ('address', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
