# Generated by Django 4.0.4 on 2022-06-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_sociallink_behance_remove_sociallink_dribble_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityform',
            name='identiy_num',
            field=models.CharField(max_length=150, verbose_name='CNIC / Passport / NIN / SSN'),
        ),
    ]
