# Generated by Django 4.0.4 on 2022-06-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_identityform_identiy_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityform',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
