# Generated by Django 4.0.4 on 2022-06-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_identityform_answered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identityform',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='identityform',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
