# Generated by Django 4.0.4 on 2022-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_identityform_options_identityform_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityform',
            name='status',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('On Review', 'On Review')], max_length=200, null=True),
        ),
    ]
