# Generated by Django 4.0.4 on 2022-06-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_identityform_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityform',
            name='accepted',
        ),
    ]
