# Generated by Django 4.0.4 on 2022-06-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_remove_identityform_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityform',
            name='status',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('On Review', 'On Review')], default='On Review', max_length=200),
        ),
    ]
