# Generated by Django 4.0.4 on 2022-07-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_user_user_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_ratings_floor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
