# Generated by Django 4.0.4 on 2022-07-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_user_user_ratings_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeleteRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
