# Generated by Django 4.0.4 on 2022-07-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_userdeleterecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others'), ('Not Specify', 'Not Specify')], default='Male', max_length=100, null=True),
        ),
    ]
