# Generated by Django 4.0.4 on 2022-07-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
