# Generated by Django 4.0.4 on 2022-07-28 09:30

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='AF', max_length=2),
        ),
    ]
